Repository apollographql/apollo-mcp-server, pull requests merged in 2025-09, with the labels that each got.

#312 Sync main → develop (PR #310)
  .github/workflows/prep-release.yml
  docs/source/best-practices.mdx
  docs/source/command-reference.mdx
  docs/source/guides/index.mdx
  docs/source/index.mdx
  docs/source/install.mdx
  docs/source/limitations.mdx
  docs/source/quickstart.mdx
Labels: back-merge, automation

#333 Sync main → develop (PR #331)
  .changesets/feat_alocay_add_basic_e2e_test.md
  .changesets/fix_fix_validate_exec_doc_validation.md
  .changesets/fix_missing_token_propagation.md
  .changesets/maint_hardcoded_versions.md
  .changesets/maint_snapshot_format.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  docs/source/install.mdx
  scripts/nix/install.sh
  scripts/windows/install.ps1
Labels: skip-changeset, back-merge, automation

#317 fix(deps): update rust crate tracing-subscriber to v0.3.20 [security]
  Cargo.lock
Labels: :christmas_tree: dependencies, vulnerability

#364 Sync main → develop (resolve conflicts)
  CHANGELOG.md
  CHANGELOG_SECTION.md
  Cargo.lock
  Cargo.toml
  docs/source/deploy.mdx
  docs/source/index.mdx
  docs/source/install.mdx
  scripts/nix/install.sh
  scripts/windows/install.ps1
Labels: skip-changeset, back-merge, automation, conflicts

#378 release: v0.9.0
  .github/workflows/prep-release.yml
  .vscode/launch.json
  CHANGELOG.md
  CHANGELOG_SECTION.md
  Cargo.lock
  Cargo.toml
  crates/apollo-mcp-registry/src/platform_api/operation_collections/collection_poller.rs
  crates/apollo-mcp-registry/src/uplink.rs
  crates/apollo-mcp-registry/src/uplink/schema.rs
  crates/apollo-mcp-registry/src/uplink/schema/schema_stream.rs
  crates/apollo-mcp-server/Cargo.toml
  crates/apollo-mcp-server/build.rs
  crates/apollo-mcp-server/src/auth.rs
  crates/apollo-mcp-server/src/cors.rs
  crates/apollo-mcp-server/src/errors.rs
  crates/apollo-mcp-server/src/event.rs
  crates/apollo-mcp-server/src/graphql.rs
  crates/apollo-mcp-server/src/introspection/minify.rs
  crates/apollo-mcp-server/src/introspection/snapshots/apollo_mcp_server__introspection__minify__tests__minify_schema.snap
  crates/apollo-mcp-server/src/introspection/tools/introspect.rs
  crates/apollo-mcp-server/src/introspection/tools/search.rs
  crates/apollo-mcp-server/src/introspection/tools/snapshots/apollo_mcp_server__introspection__tools__search__tests__search_tool.snap
  crates/apollo-mcp-server/src/introspection/tools/testdata/schema.graphql
  crates/apollo-mcp-server/src/introspection/tools/validate.rs
  crates/apollo-mcp-server/src/lib.rs
  crates/apollo-mcp-server/src/main.rs
  crates/apollo-mcp-server/src/meter.rs
  crates/apollo-mcp-server/src/operations/operation.rs
  crates/apollo-mcp-server/src/operations/operation_source.rs
  crates/apollo-mcp-server/src/runtime.rs
  crates/apollo-mcp-server/src/runtime/config.rs
  crates/apollo-mcp-server/src/runtime/filtering_exporter.rs
  crates/apollo-mcp-server/src/runtime/logging.rs
  crates/apollo-mcp-server/src/runtime/telemetry.rs
  crates/apollo-mcp-server/src/runtime/telemetry/sampler.rs
  crates/apollo-mcp-server/src/server.rs
  crates/apollo-mcp-server/src/server/states.rs
  crates/apollo-mcp-server/src/server/states/running.rs
  crates/apollo-mcp-server/src/server/states/starting.rs
  crates/apollo-mcp-server/src/telemetry_attributes.rs
  crates/apollo-mcp-server/telemetry.toml
  docs/source/_sidebar.yaml
  docs/source/config-file.mdx
  docs/source/cors.mdx
  docs/source/define-tools.mdx
  docs/source/telemetry.mdx
  e2e/mcp-server-tester/run_tests.sh
  scripts/nix/install.sh
  scripts/windows/install.ps1
Labels: release

#400 Sync main → develop (PR #398)
  CHANGELOG.md
Labels: skip-changeset, back-merge, automation
