Repository apollographql/apollo-mcp-server, pull requests merged in 2025-08, with the labels that each got.

#295 Sync main → develop (resolve conflicts)
  .github/renovate.json5
  .github/workflows/sync-develop.yml
  .github/workflows/verify-changeset.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/apollo-mcp-server/src/graphql.rs
  crates/apollo-mcp-server/src/operations.rs
  docs/source/install.mdx
  scripts/nix/install.sh
  scripts/windows/install.ps1
Labels: skip-changeset, back-merge, automation, conflicts

#303 Fix missing token propagation
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/apollo-mcp-server/src/graphql.rs
  crates/apollo-mcp-server/src/server/states/running.rs
  docs/source/install.mdx
  scripts/nix/install.sh
  scripts/windows/install.ps1
Labels: skip-changeset

#306 Sync main → develop (PR #304)
  .github/workflows/sync-develop.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/apollo-mcp-server/src/graphql.rs
  docs/source/command-reference.mdx
  docs/source/install.mdx
  scripts/nix/install.sh
  scripts/windows/install.ps1
Labels: back-merge, automation
